name: Firebase Deployment

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy
      run: |
        yarn add firebase-tools
        yarn build
        firebase deploy --token "1//0ckFc6ZvkUDg3CgYIARAAGAwSNwF-L9Ir5SlSlE-yrJaf1PVJKvUGE2_uxY0gpoUbS1t26kZGB4dfyRMucIHrSFYwz2evWjUzGvw" --project "kth-canvas-tool"
        
